# Generated by Django 6.0.6 on 2026-08-02 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('results', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAccess', models.TimeField(default=django.utils.timezone.now)),
                ('latestTime', models.TimeField(default=django.utils.timezone.now)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_task', to='api.task')),
            ],
        ),
    ]
