# Generated by Django 6.0.6 on 2026-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reservationFor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='latestTime',
            field=models.BigIntegerField(default=1785960663),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='timeOfAccess',
            field=models.BigIntegerField(default=1785960663),
        ),
    ]
